server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar_auth
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always


jwt:
  secret: "hjd7f$#3ajLz9XPp!3qVmUc@V7gXkPgZ23mZn8wQ9tPfLs#4Nk"
  expiration-ms: 86400000  # 24h
