spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar_vehicle
    username: postgres
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev

server:
  port: 8083  # Puerto del vehicle-service

customer:
  service:
    url: http://localhost:8084  # URL real del customer-service

reservation:
  service:
    url: http://localhost:8082  # URL del reservation-service

resilience4j:
  circuitbreaker:
    instances:
      reservationService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: "hjd7f$#3ajLz9XPp!3qVmUc@V7gXkPgZ23mZn8wQ9tPfLs#4Nk"
  expiration-ms: 86400000  # 24h
