spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rent_a_car
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083
customer:
  service:
    url: http://localhost:8081  # or the Eureka service name if using service discovery
resilience4j:
  circuitbreaker:
    instances:
      customerService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
reservation:
  service:
    url: http://localhost:8082