spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar_vehicle  # o el nombre que elijas
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev

server:
  port: 8083

reservation:
  service:
    url: http://localhost:8082

resilience4j:
  circuitbreaker:
    instances:
      reservationService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: "hjd7f$#3ajLz9XPp!3qVmUc@V7gXkPgZ23mZn8wQ9tPfLs#4Nk"
#  expiration-ms: 86400000  # 24h