labels:
  - name: customer
    description: Anything related to CustomerService
    color: 2ECC71

  - name: vehicle
    description: Anything related to VehicleService
    color: 3498DB

  - name: reservation
    description: For issues in ReservationService
    color: 9B59B6

  - name: auth
    description: JWT auth, login, and user flows
    color: E67E22

  - name: gateway
    description: API Gateway, routing, filters
    color: 1ABC9C

  - name: config
    description: Spring Cloud Config / shared properties
    color: 95A5A6

  - name: blocked
    description: Blocked by another task or issue
    color: E74C3C

  - name: ready for review
    description: Awaiting code review
    color: 1ABC9C

  - name: on hold
    description: Paused or waiting for rescheduling
    color: BDC3C7

  - name: roadmap
    description: Part of the roadmap or planning
    color: 8E44AD

  - name: epic
    description: Large feature spanning multiple issues
    color: 2C3E50

  - name: research
    description: Requires investigation or exploration
    color: 27AE60