labels:
  # 🧩 Feature / Microservice Labels
  - name: customer
    description: Anything related to CustomerService
    color: 2ECC71
  - name: vehicle
    description: Anything related to VehicleService
    color: 3498DB
  - name: reservation
    description: For issues in ReservationService
    color: 9B59B6
  - name: auth
    description: JWT auth, login, and user flows
    color: E67E22
  - name: gateway
    description: API Gateway, routing, filters
    color: 1ABC9C
  - name: config
    description: Spring Cloud Config / shared properties
    color: 95A5A6

  # 📦 Infrastructure & DevOps
  - name: infra
    description: DevOps, CI/CD, Docker, monitoring
    color: 34495E
  - name: docker
    description: Docker or container-related issues
    color: 0E76A8
  - name: ci/cd
    description: Continuous integration and delivery
    color: 7F8C8D

  # 🧪 Testing & QA
  - name: tests missing
    description: Needs unit or integration tests
    color: C0392B
  - name: test failure
    description: Failing test or flaky behavior
    color: E74C3C
  - name: qa
    description: Ready for QA or manual testing
    color: F39C12

  # 🎯 Priority
  - name: "priority: high"
    description: Must complete for release
    color: C0392B
  - name: "priority: medium"
    description: Important but not critical
    color: F39C12
  - name: "priority: low"
    description: Nice to have
    color: BDC3C7

  # 🧠 Planning / Meta
  - name: roadmap
    description: Part of the roadmap or planning
    color: 8E44AD
  - name: epic
    description: Large feature spanning multiple issues
    color: 2C3E50
  - name: research
    description: Requires investigation or exploration
    color: 27AE60
