version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rentacar-postgres
    restart: always
    environment:
      POSTGRES_DB: rentacar_vehicle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: rentacar-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rentacar.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"

volumes:
  postgres_data:
