server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: reservation-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/reservations/**
        - id: vehicle-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/vehicles/**
        - id: customer-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/customers/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
