spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar_customer
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8084
jwt:
  secret: "hjd7f$#3ajLz9XPp!3qVmUc@V7gXkPgZ23mZn8wQ9tPfLs#4Nk"
  expiration-ms: 86400000  # 24h