server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar_payment
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

reservation-client:
  ribbon:
    listOfServers: http://localhost:8082

feign:
  client:
    config:
      default:
        loggerLevel: full

resilience4j:
  circuitbreaker:
    instances:
      reservation-service:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
