server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar_reservation
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
