spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rent_a_car
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
server:
  port: 8082
