# .github/workflows/angular.yml
name: Angular Frontend CI

on:
  push:
    paths:
      - 'rentacar-frontend/**'
  pull_request:
    paths:
      - 'rentacar-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rentacar-frontend

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
